---
apiVersion: v1
kind: Secret
metadata:
  name: sdc-cs-secret
  namespace: onap-sdc
type: Opaque
data:
    #application user
    sdc_user: {{ required "secrets.sdc_user must be set (base64)" .Values.secrets.sdc_user | quote }}
    sdc_password: {{ required "secrets.sdc_password must be set (base64)" .Values.secrets.sdc_password | quote }}
    #default user:
    cs_password: {{ required "secrets.cs_password must be set (base64)" .Values.secrets.cs_password | quote }}
    
